spring.application.name=ecommerce-backend

# Database Connection
# --- DATABASE CONFIGURATION ---
# Uses Render variables if they exist; otherwise falls back to your local 'medidark' DB.
spring.datasource.url=jdbc:postgresql://34.44.76.11:5432/altair
spring.datasource.username=postgres
spring.datasource.password=Altair-backend-2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8081}
razorpay.key.id=rzp_test_SivyKsVqMFlgVa
razorpay.key.secret=eIIO9Ss5eppmnV2Ep3WuVrvQ
# --- CORS ORIGIN ---
# Uses the Render variable if you set it later; otherwise defaults to your local React app.


# Execute data.sql ONLY if tables are dropped/recreated, not on update
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
